# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a155e9a1c77abdf4e84a3c81b836e9ebe9a4711047b5aca5444b8fa9a9fb38975a07910a7bebda59d01abc967aaf5f25697ce4211e869a050dfe6d47fd9d4d8e

test:
  secret_key_base: 8d2d8c174ea8db70af57e5ffbf20c6545254675479a4c9a61dcf1623355b62347836bf0d1268680d257ffc18ac92338b914cd8a71def66baba1ea3af5b661992

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
